// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjfb-Aj8OZv4_QsrFMtn_mDRwH6DC8TEY',
    appId: '1:426256480277:web:bdc69568d4379fb827761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    authDomain: 'bay-yahe-9f408.firebaseapp.com',
    storageBucket: 'bay-yahe-9f408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxfj7kJ84evqltYvO4I_lbZi0bP9KqvA',
    appId: '1:426256480277:android:c7e13f1c8436b75c27761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    storageBucket: 'bay-yahe-9f408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4yysTFHXCL7qT7Sjt-n5q1X2984NddI',
    appId: '1:426256480277:ios:9aad7597985ee5f627761c',
    messagingSenderId: '426256480277',
    projectId: 'bay-yahe-9f408',
    storageBucket: 'bay-yahe-9f408.appspot.com',
    iosBundleId: 'com.example.bayYaheApp',
  );
}
